version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb_container
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - node-network
  node-app:
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/easymediadb
    ports:
      - '3000:3000'
    depends_on:
      - mongodb_container
    volumes:
      - .:/app
    networks:
      - node-network
volumes:
  mongodb_data_container:
networks:
  node-network:
    driver: bridge