version: '3.7'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: db_container
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  api:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: easymediadb
      NODE_PORT: 3000
    depends_on: 
      - mongodb
volumes:
  mongodb_data_container: